name: Trigger Other Repo
on:
  schedule:
    - cron: '0 10 * * *' # Hafta içi her gün saat 12:00'da tetiklenir.(utc:10:00 cest:12:00 denk gelir.)

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check Time and Set Environment Variable
      id: check_time
      run: |
        current_hour=$(date +'%H')
        current_day=$(date +'%u')
        if [ "$current_hour" -ge 12 ] && [ "$current_day" -lt 6 ]; then
          echo "It is after 12 PM on a weekday"
          echo "AFTER_NOON=true" >> $GITHUB_ENV
        else
          echo "It is before 12 PM or weekend"
          echo "AFTER_NOON=false" >> $GITHUB_ENV
        fi
    - name: Trigger Other Repo
      if: env.AFTER_NOON == 'true'
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
        https://api.github.com/repos/sumeyyekoruyucu/stajgithubactionsdeneme/dispatches \
        -d '{"event_type":"trigger_workflow"}'