name: Node.js Project Deployment

on:
  schedule:
    - cron: '* * * * *' # Çift saatlerde tetiklenir

jobs:
  deploy-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Print Local Time
      run: |
        local_time=$(date +'%Y-%m-%d %H:%M:%S %Z')
        echo "Local Time: $local_time"

    - name: Install PM2
      run: npm install -g pm2

    - name: Install Dependencies
      run: |
        cd my-node-app
        npm install

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        cd my-node-app
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku HEAD:main --force

    - name: Start Application
      run: |
        cd my-node-app     
        pm2 start app.js
        pm2 save

    - name: Verify Deployment
      run: |
        cd my-node-app
        pm2 list