name: Trigger Other Repo
on:
  schedule:
    - cron: '12 20 * * 1-5' # Hafta içi her gün saat 12:00'da tetiklenir
jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Check Time and Trigger Other Repo
      id: check_time
      run: |
        current_hour=$(date +'%H')
        current_day=$(date +'%u')
        if [ "$current_hour" -ge 12 ] && [ "$current_day" -lt 6 ]; then
          echo "It is after 12 PM on a weekday"
          echo "::set-output name=after_noon::true"
        else
          echo "It is before 12 PM or weekend"
          echo "::set-output name=after_noon::false"
        fi
    - name: Trigger Other Repo
      if: steps.check_time.outputs.after_noon == 'true'
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
        https://api.github.com/repos/sumeyyekoruyucu/stajgithubactionsdeneme/dispatches \
        -d '{"event_type":"trigger_workflow"}'