name: Node.js Project Deployment
on:
  schedule:
    - cron: '0 */2 * * *' # Çift saatlerde tetiklenir

jobs:
  deploy-node:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Dependencies
      run: npm install
    - name: Start Application
      run: |
        pm2 start app.js
        pm2 save
    - name: Verify Deployment
      run: pm2 list