name: Deploy Docker to EC2

on:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy Docker to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo yum update -y
          sudo yum install -y amazon-linux-extras
          sudo yum install -y docker
          sudo systemctl start docker.service
          sudo usermod -a -G docker ec2-user
          docker --version