name: Deploy Docker to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode SSH Key
      id: decode_key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ssh_key
        chmod 600 ssh_key

    - name: Install Docker on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ssh_key
        script: |
          echo "merhaba"
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo usermod -a -G docker $USER
          docker --version