name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: '16' # İlk olarak bir Node.js sürümü kuruyoruz

      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
          echo "source $HOME/.nvm/nvm.sh" >> $GITHUB_ENV
          echo "source $HOME/.nvm/bash_completion" >> $GITHUB_ENV
    
      - name: Install specific Node.js versions
        run: |
          source $HOME/.nvm/nvm.sh
          versions=("10" "12" "14" "16" "18" "20")
          for version in "${versions[@]}"; do
            nvm install $version
          done
          nvm ls
    

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Set up SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/linux_key_5.pem
          chmod 400 ~/.ssh/linux_key_5.pem

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to EC2 and deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/linux_key_5.pem $EC2_USER@$EC2_HOST << 'EOF'
          set -e
          set -x

          # Update the instance and install necessary packages
          sudo yum update -y --skip-broken
          sudo yum install -y git

          # Clone or pull the GitHub repository
          if [ ! -d "githubactions_deneme" ]; then
              git clone https://github.com/sumeyyekoruyucu/githubactions_deneme.git
          else
              echo " Varolan dizini güncellemek için 'githubactions_deneme' dizinine gidin ve 'git pull' komutunu kullanın."
              cd githubactions_deneme
              git pull origin main  # or the appropriate branch
          fi

          # Navigate to the application directory and install dependencies
          cd /home/ec2-user/githubactions_deneme/my-node-app
          sudo amazon-linux-extras install epel
          sudo yum repolist
          curl -fsSL https://nodejs.org/dist/latest-v16.x/node-v14.x.x-linux-x64.tar.xz -o node-v16.x.x-linux-x64.tar.xz
          sudo tar -xJf node-v16.x.x-linux-x64.tar.xz -C /usr/local --strip-components=1
          sudo node -v
          sudo npm -v

          # Start the application using PM2
          sudo npm install -g pm2
          sudo pm2 start app.js --name my-node-app

          # Configure Nginx
          sudo amazon-linux-extras install nginx1 -y
          sudo systemctl enable nginx
          sudo systemctl start nginx
          sudo bash -c 'cat > /etc/nginx/conf.d/my-node-app.conf' << EOL
          server {
              listen 80;
              server_name sumeyyedev.site;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }
          EOL
          sudo nginx -t && sudo systemctl restart nginx
          EOF