name: Node.js Project Deployment
on:
  schedule:
    - cron: '* * * * *' # Çift saatlerde tetiklenir

jobs:
  deploy-node:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Dependencies
      run: |
        cd my-node-app
        npm install

    - name: Start Application
      run: |
        cd my-node-app
        pm2 start app.js
        pm2 save

    - name: Verify Deployment
      run: |
        cd my-node-app
        pm2 list