name: React Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
    
      - name: Load nvm and install specific Node.js version
        run: |
          export NVM_DIR=$HOME/.nvm
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 16
          nvm use 16

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Set up SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/linux_key_5.pem
          chmod 400 ~/.ssh/linux_key_5.pem

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to EC2 and deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/linux_key_5.pem $EC2_USER@$EC2_HOST << 'EOF'
          set -e
          set -x

          # Update the instance and install necessary packages
          sudo yum update -y --skip-broken
          sudo yum install -y git

          # Clone or pull the GitHub repository
          if [ ! -d "/home/ec2-user/githubactions_deneme" ]; then
              git clone https://github.com/sumeyyekoruyucu/githubactions_deneme.git /home/ec2-user/githubactions_deneme
          else
              cd /home/ec2-user/githubactions_deneme
              git pull origin main
          fi

          # Install dependencies and build react
          cd /home/ec2-user/githubactions_deneme/react
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install 16
          nvm use 16
          npm install
          npm run build
          npm install -g pm2
          npm install -g serve

          # Start the React app using pm2
          pm2 start npx --name "react-app" -- serve -s build -l 3000
          pm2 save
          pm2 startup systemd -u ec2-user --hp /home/ec2-user

          # Check PM2 status
          pm2 status

          # Configure Nginx
          sudo amazon-linux-extras install nginx1 -y
          sudo systemctl enable nginx
          sudo systemctl start nginx
          sudo bash -c 'cat > /etc/nginx/conf.d/react.conf' << EOL
          server {
              listen 80;
              server_name sumeyyedev.site;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }
          EOL
          sudo nginx -t
          sudo systemctl restart nginx
          
          # Check Nginx status
          sudo systemctl status nginx
          EOF