name: Deploy to Render

on:
  push:
    branches:
      - main  # veya ana dal adınızı buraya yazın

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Render
        uses: <render-deploy-action>  # Render için uygun deploy eylemi buraya gelir, Render'in GitHub Actions entegrasyonunu kullanabilirsiniz

      # Diğer adımlar veya gereksinimler buraya eklenir