name: Node.js Project Render Deployment

on:
  schedule:
    - cron: '* * * * *' # Her dakikada tetiklenir

jobs:
  deploy-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Print Local Time
      run: |
        local_time=$(date +'%Y-%m-%d %H:%M:%S %Z')
        echo "Local Time: $local_time"

    - name: Install PM2
      run: npm install -g pm2

    - name: Install Dependencies
      run: |
        cd my-node-app
        npm install
        npm start

    - name: Start Application
      run: |
        cd my-node-app     
        pm2 start app.js
        pm2 save

    - name: Verify Deployment
      run: |
        cd my-node-app
        pm2 list

    #- name: Deploy to Render
    #  run: |
    #    curl -X POST \
    #    -H "Accept: application/vnd.github.v3+json" \
    #    -H "Authorization: token ${{ secrets.RENDER_API_KEY }}" \
    #    https://api.render.com/v1/services/srv-cq8i2mij1k6c73clg8vg?key=fx1p_zhIBVs/deploys
    - name: Deploy to Render
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}