name: Create and Deploy React App to Render

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *' 

jobs:
  create-and-deploy-react:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install create-react-app globally
      run: npm install -g create-react-app

    - name: Create React App
      run: npx create-react-app my-react-app

    - name: Change Directory to React App
      run: cd my-react-app

    - name: Install Dependencies
      run: yarn install

    - name: Build Project
      run: yarn build

    - name: Deploy to Render
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys