name: Java Smoke Test

on:
  push:
    branches: 
      - develop 
  pull_request:
    branches:
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.verify.outputs.exitcode }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3  # Güncelleme yapıldı

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: 'maven'

      - name: Get Chrome version
        run: |
          LATEST_CHROME_VERSION=$(google-chrome --version | grep -oP '(?<=Google Chrome )[0-9]+')
          LATEST_CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$LATEST_CHROME_VERSION)
          echo "Latest Chrome version: $LATEST_CHROME_VERSION"
          echo "Latest ChromeDriver version: $LATEST_CHROMEDRIVER_VERSION"
          echo "::set-env name=CHROMEDRIVER_VERSION::$LATEST_CHROMEDRIVER_VERSION"
        shell: bash

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          chromedriver --version
        if: runner.os == 'Linux'

      - name: Install wkhtmltopdf
        run:  sudo apt-get install -y wkhtmltopdf

      - name: salevali giris
        run: |
          echo "email=${{ secrets.EMAIL }}" >> configuration.properties
          echo "password=${{ secrets.PASSWORD }}" >> configuration.properties
          echo "url=${{ secrets.URL }}" >> configuration.properties
          echo "browser=${{ secrets.BROWSER }}" >> configuration.properties
          
      - name: Set up Node.js 20
        uses: actions/setup-node@v3  # Güncelleme yapıldı
        with:
          node-version: '20'
          cache: 'npm'

      - name: verify Maven
        id: verify
        run: | 
          set +e
          mvn clean verify -f "pom.xml"                 
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"
        continue-on-error: true

      - name: Generate PDF Report
        run: |
          wkhtmltopdf --enable-local-file-access ${{ github.workspace }}/target/cucumber-html-reports/overview-features.html test_report.pdf
      - name: Create Directory and copy PDF to Directory
        run: |
          mkdir -p desired/path/
          cp ${{ github.workspace }}/test_report.pdf desired/path/test_report.pdf
      
      - uses: actions/upload-artifact@master
        with:
          name: my-test_report-file
          path: desired/path        

  email:
      runs-on: ubuntu-latest
      needs: [ build ]
      steps:
      - name: Write Exit Code
        run: printf "%s\n" "${{ needs.build.outputs.exitcode }}"

      - uses: actions/download-artifact@master
        with:
          name: my-test_report-file
          path: desired/path

      - name: Send Mail                
        if: ${{ needs.build.outputs.exitcode!=0 }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: ${{ secrets.SERVER_ADDRESS}}
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: simsek@bcsit-gmbh.de
          body: |
            The Job named ${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }}:
            Test failed. Test Report is in attachment!
          attachments: |
              desired/path/test_report.pdf
