name: Tag Triggered Workflow

on:
  push:
    tags:
      - 'node'  # 'node' adlı etikette bu iş akışı çalışır

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Some Command
        run: echo "Tag a gore akisi calistirdi."